name: Deploy Automático

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Permite push na branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências (opcional)
        run: |
          echo "Nenhuma dependência necessária para HTML puro"

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # publica a raiz (onde está o index.html)
