name: CI/CD - Teste e Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar pytest (se precisar)
        run: python -m pip install --upgrade pip pytest

      - name: Executar testes
        run: |
          if [ -f "test_*.py" ] || [ -f "*_test.py" ] || ls tests/*.py 1>/dev/null 2>&1; then
            python -m pytest -v
          else
            echo "Sem testes definidos — seguindo para o deploy"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()    # só publica se os testes passarem
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
