name: Teste CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Atualizar pip e instalar pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Executar script principal
        run: python main.py

      - name: Executar testes
        run: python -m pytest -v
